### ISSUE TITLE
Latest version is not available on conda-forge

### ISSUE THREAD

**Issue by auneri** [conda-forge/metaimageio-feedstock#5]
### Comment:

Hi @conda-forge/core, I released a new version of this project last week, but I do not see the updated package on conda-forge. Any help or guidance would be appreciated.

**Comment by beckermr** [comment]
We had a bot bug that backlogged a bunch of version PRs. It should come in a few days but for now you can do the bump yourself too.

**Comment by auneri** [comment]
Thank you for the very quick response!
Happy to wait a few days. I will close this issue once the package is available.

**Comment by auneri** [comment]
Skipped v1.1.3, published v1.1.4.

**Comment by jakirkham** [comment]
Sorry a bit confused. Wasn't 1.1.3 done in PR ( https://github.com/conda-forge/metaimageio-feedstock/pull/4 )?

**Comment by auneri** [comment]
Hi @jakirkham, thanks for checking. Yes, it was, but the package never made it to [conda-forge](https://anaconda.org/conda-forge/metaimageio/files), possibly due to the bot bug @beckermr mentioned.

**Comment by jakirkham** [comment]
The bot issue would explain if no PR showed up, but the PR exists

More likely there was a GH webhook outage (what triggers CI) or an Azure outage. Starting a fresh CI build may help

Edit: Here's [a new CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=670909&view=results ) for commit ( https://github.com/conda-forge/metaimageio-feedstock/commit/c3e43bd51b5c8a290178025af613a4e9c1f45112 ) on `main` where PR ( https://github.com/conda-forge/metaimageio-feedstock/pull/4 ) was merged. Admittedly not as relevant now

Edit 2: Looks like that build completed and added [a new package]( https://anaconda.org/conda-forge/metaimageio/files?version=1.1.3 )

**Comment by auneri** [comment]
Oh, that is good to hear!

The latest version includes a minor fix, so as long as the latest version is fetched by default (and not the latest upload date), all should be good. Thank you both for the **excellent** support!

**Comment by jakirkham** [comment]
Yeah users would still get the latest version unless there was some constraint that caused a different version to be preferred
